apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portainer
spec:
  rules:
    - host: portainer.{{DOMAIN}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portainer
                port:
                  number: 30777